"""
PALISADE -- security and safety mediation sidecar for VISTA's agent
runtime.

"""

from palisade.capabilities import (
    CapabilityRegistry,
    CapabilityTag,
    DualUseMarker,
    SensitivityTier,
    TrustTier,
)
from palisade.config import PalisadeSettings
from palisade.gates import (
    DEFAULT_QUERY_INJECTION_PATTERNS,
    HIGH_STAKES_FALLBACK,
    KB_POLICY_FILENAME,
    KB_POLICY_VERSION,
    AnomalyResult,
    G2ToolGate,
    G3RagGate,
    Gate,
    GateContext,
    GateDecision,
    KbPolicy,
    MirroredRetrievalResult,
    ParsedChunk,
    PassThroughGate,
    SanitizedChunk,
    ToolDescriptor,
    ToolMetadata,
    detect_embedding_anomalies,
    discover_high_stakes_tools,
    discover_tool_metadata,
    hash_chunk,
    inject_hybrid_args,
    load_kb_policy,
    merge_retrievals,
    parse_rag_search_result,
    should_inject_hybrid,
    tag_rag_chunks,
    tag_sanitized_rag_chunks,
)
from palisade.incidents import IncidentManager, IncidentRecord
from palisade.provenance import ProvenanceEmitter, ProvenanceEvent
from palisade.quarantine import (
    QUARANTINE_SYSTEM_PROMPT,
    QuarantineDecision,
    build_quarantine_agent,
    run_quarantine_with_self_consistency,
)
from palisade.sidecar import PalisadeSidecar
from palisade.tool_registry import (
    HashVerification,
    MANIFEST_FILENAME,
    ToolDescriptorRegistry,
    canonical_descriptor,
    hash_descriptor,
    hash_tool_descriptor,
    load_manifest,
    write_manifest,
)
from palisade.trust import TierPolicy, TrustScorer

__all__ = [
    "AnomalyResult",
    "CapabilityRegistry",
    "CapabilityTag",
    "DEFAULT_QUERY_INJECTION_PATTERNS",
    "DualUseMarker",
    "G2ToolGate",
    "G3RagGate",
    "Gate",
    "GateContext",
    "GateDecision",
    "HIGH_STAKES_FALLBACK",
    "HashVerification",
    "IncidentManager",
    "IncidentRecord",
    "KB_POLICY_FILENAME",
    "KB_POLICY_VERSION",
    "KbPolicy",
    "MANIFEST_FILENAME",
    "MirroredRetrievalResult",
    "ParsedChunk",
    "PassThroughGate",
    "ProvenanceEmitter",
    "SanitizedChunk",
    "ProvenanceEvent",
    "QUARANTINE_SYSTEM_PROMPT",
    "QuarantineDecision",
    "SensitivityTier",
    "TierPolicy",
    "ToolDescriptor",
    "ToolDescriptorRegistry",
    "ToolMetadata",
    "TrustScorer",
    "TrustTier",
    "PalisadeSettings",
    "PalisadeSidecar",
    "build_quarantine_agent",
    "canonical_descriptor",
    "detect_embedding_anomalies",
    "discover_high_stakes_tools",
    "discover_tool_metadata",
    "hash_chunk",
    "hash_descriptor",
    "hash_tool_descriptor",
    "inject_hybrid_args",
    "load_kb_policy",
    "load_manifest",
    "merge_retrievals",
    "parse_rag_search_result",
    "run_quarantine_with_self_consistency",
    "should_inject_hybrid",
    "tag_rag_chunks",
    "tag_sanitized_rag_chunks",
    "write_manifest",
]