"""
PALISADE gate implementations.
"""

from palisade.gates.base import Gate, GateContext, GateDecision, PassThroughGate
from palisade.gates.g1_prompt import (
    CUI_MARKER_PATTERNS,
    DEFAULT_ALLOWED_MIME_TYPES,
    DEFAULT_MAX_FILE_SIZE_BYTES,
    G1PromptGate,
    JAILBREAK_SIGNATURES_FILENAME,
    PII_PATTERNS,
    load_jailbreak_signatures,
)
from palisade.gates.g2_tool import (
    HIGH_STAKES_FALLBACK,
    G2ToolGate,
    ToolDescriptor,
    ToolMetadata,
    discover_high_stakes_tools,
    discover_tool_metadata,
)
from palisade.gates.g4_code import (
    DEFAULT_SEMGREP_CONFIG,
    DEFAULT_SEMGREP_TIMEOUT_SECONDS,
    DEFAULT_WRITE_ROOTS,
    RUN_TOOLS,
    WRITE_TOOLS,
    ExtractedCode,
    G4CodeGate,
    G4SandboxCodeGate,
    SemgrepFinding,
    bundled_rules_dir,
    run_bash_violation,
    write_path_violation,
)
from palisade.gates.g5_hpc import (
    ALLOCATION_POLICY_FILENAME,
    ALLOCATION_POLICY_VERSION,
    DEFAULT_CREDENTIAL_PATTERNS,
    DEFAULT_HOST_ALLOW_LIST,
    DEFAULT_MINING_BINARY_DENYLIST,
    DEFAULT_MINING_SIGNATURES,
    DEFAULT_SENSITIVE_PATH_PATTERNS,
    AllocationLimits,
    AllocationPolicy,
    G5HpcJobGate,
    load_allocation_policy,
)
from palisade.gates.slurm_parser import (
    DependencyRef,
    ParsedCommand,
    SbatchDirectives,
    SlurmScript,
    parse_slurm_script,
    parse_slurm_time,
)
from palisade.gates.g3_anomaly import AnomalyResult, detect_embedding_anomalies
from palisade.gates.g3_hybrid import (
    MirroredRetrievalResult,
    inject_hybrid_args,
    merge_retrievals,
    should_inject_hybrid,
)
from palisade.gates.g3_rag import (
    DEFAULT_QUERY_INJECTION_PATTERNS,
    G3RagGate,
    KB_POLICY_FILENAME,
    KB_POLICY_VERSION,
    KbPolicy,
    ParsedChunk,
    SanitizedChunk,
    hash_chunk,
    load_kb_policy,
    parse_rag_search_result,
    tag_rag_chunks,
    tag_sanitized_rag_chunks,
)
from palisade.gates.g6_egress import G6EgressGate

__all__ = [
    "ALLOCATION_POLICY_FILENAME",
    "ALLOCATION_POLICY_VERSION",
    "AllocationLimits",
    "AllocationPolicy",
    "AnomalyResult",
    "CUI_MARKER_PATTERNS",
    "DEFAULT_CREDENTIAL_PATTERNS",
    "DEFAULT_HOST_ALLOW_LIST",
    "DEFAULT_MINING_BINARY_DENYLIST",
    "DEFAULT_MINING_SIGNATURES",
    "DEFAULT_SENSITIVE_PATH_PATTERNS",
    "DependencyRef",
    "G5HpcJobGate",
    "ParsedCommand",
    "SbatchDirectives",
    "SlurmScript",
    "load_allocation_policy",
    "parse_slurm_script",
    "parse_slurm_time",
    "DEFAULT_ALLOWED_MIME_TYPES",
    "DEFAULT_MAX_FILE_SIZE_BYTES",
    "DEFAULT_QUERY_INJECTION_PATTERNS",
    "DEFAULT_SEMGREP_CONFIG",
    "DEFAULT_SEMGREP_TIMEOUT_SECONDS",
    "DEFAULT_WRITE_ROOTS",
    "ExtractedCode",
    "G1PromptGate",
    "G2ToolGate",
    "G3RagGate",
    "G4CodeGate",
    "G4SandboxCodeGate",
    "G6EgressGate",
    "Gate",
    "GateContext",
    "GateDecision",
    "HIGH_STAKES_FALLBACK",
    "JAILBREAK_SIGNATURES_FILENAME",
    "KB_POLICY_FILENAME",
    "KB_POLICY_VERSION",
    "KbPolicy",
    "MirroredRetrievalResult",
    "PII_PATTERNS",
    "ParsedChunk",
    "PassThroughGate",
    "SanitizedChunk",
    "SemgrepFinding",
    "ToolDescriptor",
    "ToolMetadata",
    "bundled_rules_dir",
    "detect_embedding_anomalies",
    "discover_high_stakes_tools",
    "discover_tool_metadata",
    "hash_chunk",
    "inject_hybrid_args",
    "load_jailbreak_signatures",
    "load_kb_policy",
    "merge_retrievals",
    "parse_rag_search_result",
    "should_inject_hybrid",
    "tag_rag_chunks",
    "tag_sanitized_rag_chunks",
    "RUN_TOOLS",
    "WRITE_TOOLS",
    "run_bash_violation",
    "write_path_violation",
]